server {
    listen 80 default_server;

    resolver 127.0.0.1 valid=30s;   # DNS resolver for dynamic hostnames

    #Redirect to add the trailing / (for assets with relative URL to load correctly)
    location ~ ^/([^/]+)$ {
        return 301 /$1/;
    }
    #proxies the URL http://vpn.waziup.org/wazigate-<id>/XXX to local URL http://wazigate-<id>/XXX
    location ~ ^/([^/]+)/?(.*)$ {
        set $target $1;
        set $rest $2;

        proxy_pass http://$target/$rest;

        proxy_set_header Host $target;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}

