version: '3'

services:
  #front-end proxy for load balancer
  proxy-front:
    build: ./proxy-frontend
    image: waziup/proxy-frontend
    ports:
      - "80:80"
      - "443:443"
    network_mode: host
    volumes:
      - ./certs:/certs
    extra_hosts:
      - "website:127.0.0.1"

  dashboard-production:
    # Specific images should be built for each environment (local, staging, production).
    image: waziup/dashboard:2.1-production
    build:
      context: ./dashboard
      args:
        - SERVER_PORT=3000
        - SERVER_URL=https://dashboard.waziup.io
        - KEYCLOAK_URL=https://keycloak.waziup.io/auth
        - API_SERVER_URL=https://api.waziup.io/api
        - DOC_SERVER_URL=https://www.waziup.io/documentation/dashboard
        - NODE_ENV=production
        - DELAY_REFRESH=60000 # 60 seconds
    ports:
      - "3000:3000"

  dashboard-staging:
    # Specific images should be built for each environment (local, staging, production).
    image: waziup/dashboard:2.2-staging
    build:
      context: ./dashboard
      args:
        - SERVER_PORT=3001
        - SERVER_URL=https://staging.dashboard.waziup.io
        - KEYCLOAK_URL=https://keycloak.waziup.io/auth
        - API_SERVER_URL=https://api.waziup.io/api
        - DOC_SERVER_URL=https://www.waziup.io/documentation/dashboard
        - NODE_ENV=staging
    ports:
      - "3000:3000"
