apiVersion: v1
kind: ReplicationController
metadata:
  name: elasticsearch
  namespace: waziup
  labels:
    component: elasticsearch
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: elasticsearch
    spec:
      containers:
      - name: es
        image: waziup/elasticsearch
        env:
        - name: "ES_JAVA_OPTS"
          value: "-Xms2g -Xmx2g"
        ports:
        - containerPort: 9200
          name: http
          protocol: TCP
        - containerPort: 9300
          name: transport
          protocol: TCP
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: storage
      volumes:
      - name: storage
        hostPath:
          path: /mnt/vol/elsdata 

---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: waziup
  labels:
    component: elasticsearch
spec:
  type: NodePort
  selector:
    component: elasticsearch
  ports:
  - name: http
    port: 9200
    protocol: TCP
    nodePort: 30920
  - name: transport
    port: 9300
    protocol: TCP

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: elasticsearch
  namespace: waziup
spec:
  rules:
  - host: elasticsearch.waziup.io
    http:
      paths:
      - path: /
        backend:
          serviceName: elasticsearch
          servicePort: 9200

