apiVersion: v1
kind: ConfigMap
metadata:
  name: feeder-config2
  namespace: waziup
data:
  default.yaml: |
    endpoint:
      id: tb2
      url: http://feeder2
    
    elasticsearch:
      host: elasticsearch
      port: 9200
    
    orion:
      # MUST NOT end with slash
      uri: http://orion:1026
    
    tasks:
    - trigger: subscription
      orion:
        service: waziup
        servicePath: /#
      period: 600000
    - trigger: subscription
      orion:
        service: watersense
        servicePath: /#
      filter:
        types:   
          - Farm
    - trigger: subscription
      orion:
        service: watersense
        servicePath: /#
      filter:
        types:   
          - SensingDevice
      period: 60000
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: waziup
  name: feeder2
spec:
  replicas: 1
  template:
    metadata:
      name: feeder2
      labels:
        app: feeder2
    spec:
      containers:
      - name: feeder2
        image: waziup/feeder2
        env:
        - name: FEEDER_EXTRA_CONFIG_DIR
          value: /etc/feeder/
        ports:
        - containerPort: 8000
        volumeMounts:
        - mountPath: /etc/feeder
          name: feeder-config2
      volumes:
      - name: feeder-config2
        configMap:
          name: feeder-config2
          items:
          - key: default.yaml
            path: default.yaml

---

apiVersion: v1
kind: Service
metadata:
  namespace: waziup
  labels:
    name: feeder2
  name: feeder2
spec:
  ports:
    - port: 80
      targetPort: 9000
  selector:
    app: feeder2