apiVersion: v1
kind: ReplicationController
metadata:
  name: logstash
  namespace: waziup
  labels:
    component: logstash
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: logstash
    spec:
      containers:
      - name: es
        image: waziup/logstash 
        ports:
        - containerPort: 5000 

---
apiVersion: v1
kind: Service
metadata:
  name: logstash
  namespace: waziup
  labels:
    component: logstash
spec:
  type: NodePort
  selector:
    component: logstash
  ports:
  - name: http
    port: 5000
    protocol: TCP

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: logstash
  namespace: waziup
spec:
  rules:
  - host: logstash.waziup.io
    http:
      paths:
      - path: /
        backend:
          serviceName: logstash
          servicePort: 5000

