apiVersion: v1
kind: ReplicationController
metadata:
  name: mongo
  namespace: waziup
  labels:
    name: mongo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: mongo
    spec:
      containers:
      - name: mongo
        image: waziup/mongodb:latest
        ports:
        - containerPort: 27017
        volumeMounts:
        - mountPath: /data/db
          name: vol
      volumes:
      - name: vol
        hostPath:
          path: /mnt/vol

---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: waziup
spec:
  type: NodePort
  selector:
    name: mongo
  ports:
    - name: mongo
      port: 27017
      nodePort: 30017

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: mongo
  namespace: waziup
spec:
  rules:
  - host: brokerdb.waziup.io
    http:
      paths:
      - path: /
        backend:
          serviceName: mongo
          servicePort: 27017
