apiVersion: v1
kind: ReplicationController
metadata:
  name: orion
  namespace: waziup
  labels:
    name: orion
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: orion
    spec:
      containers:
      - name: orion
        image: waziup/orion:latest
        ports:
        - containerPort: 1026
        args: ["-dbhost", "mongo.waziup:27017", "-logLevel", "INFO"] #, "-corsOrigin", "__ALL"]

---
apiVersion: v1
kind: Service
metadata:
  name: orion
  namespace: waziup
spec:
  type: NodePort
  selector:
    name: orion
  ports:
    - name: orion
      port: 1026
      nodePort: 30026

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: orion
  namespace: waziup
spec:
  rules:
  - host: broker.waziup.io
    http:
      paths:
      - path: /
        backend:
          serviceName: orion
          servicePort: 1026
