# InnoTec21 Website
server {
    listen      443 ssl;
    server_name www.innotec21.de;
    include letsencrypt.conf;
    client_max_body_size 512M;
    location / {
        proxy_pass http://wordpress;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

# Redirect from innotec21.de to www.innotec21.de
server {
  listen      443 ssl;
  server_name innotec21.de;
  include letsencrypt.conf;
  location / {
    return 301  https://www.innotec21.de$request_uri;
  }
}