# Redirect KijaniBox domains to KijaniCooling
server {
    listen      443 ssl;
    server_name www.kijanibox.eu kijanibox.eu;
    include letsencrypt.conf;
    location / {
        return 301 https://www.kijanicooling.eu$request_uri;
    }
}