upstream osirris {
    server 18.195.197.182:3000;
}

# Osirris Website
server {
    listen      443 ssl;
    server_name osirris.waziup.io;
    include letsencrypt.conf;
    location / {
        proxy_pass http://osirris;
    }
}

