
upstream lab {
  server 35.157.161.231:8086;
}



# WaziLab (Learning Center)
# app.wazilab.io
server {
  listen      443 ssl;
  server_name app.wazilab.io;
  include     letsencrypt.conf;
  location / {
    proxy_pass http://lab;
  }
}

# Redirect from lab.waziup.io to app.wazilab.io
server {
  listen      443 ssl;
  server_name lab.waziup.io;
  include letsencrypt.conf;
  location / {
    return 301  https://app.wazilab.io$request_uri;
  }
}