{
  "executionRoleArn": null,
  "containerDefinitions": [
    {
      "dnsSearchDomains": [],
      "logConfiguration": {
        "logDriver": "awslogs",
        "options": {
          "awslogs-group": "waziup",
          "awslogs-region": "eu-central-1",
          "awslogs-stream-prefix": "orion"
        }
      },
      "entryPoint": [],
      "portMappings": [
        {
          "hostPort": 1026,
          "protocol": "tcp",
          "containerPort": 1026
        }
      ],
      "command": [
        "-dbhost",
        "mongo",
        "-logLevel",
        "INFO"
      ],
      "linuxParameters": null,
      "cpu": 0,
      "environment": [],
      "ulimits": null,
      "dnsServers": [],
      "mountPoints": [],
      "workingDirectory": null,
      "dockerSecurityOptions": [],
      "memory": 128,
      "memoryReservation": null,
      "volumesFrom": [],
      "image": "fiware/orion:1.7.0",
      "disableNetworking": null,
      "healthCheck": null,
      "essential": true,
      "links": [],
      "hostname": "orion",
      "extraHosts": [
        {
          "ipAddress": "127.0.0.1",
          "hostname": "mongo"
        }
      ],
      "user": null,
      "readonlyRootFilesystem": false,
      "dockerLabels": null,
      "privileged": false,
      "name": "orion"
    }
  ],
  "placementConstraints": [],
  "memory": null,
  "taskRoleArn": null,
  "compatibilities": [
    "EC2"
  ],
  "taskDefinitionArn": "arn:aws:ecs:eu-central-1:443027577688:task-definition/Orion:2",
  "family": "Orion",
  "requiresAttributes": [
    {
      "targetId": null,
      "targetType": null,
      "value": null,
      "name": "com.amazonaws.ecs.capability.docker-remote-api.1.17"
    },
    {
      "targetId": null,
      "targetType": null,
      "value": null,
      "name": "com.amazonaws.ecs.capability.docker-remote-api.1.18"
    },
    {
      "targetId": null,
      "targetType": null,
      "value": null,
      "name": "com.amazonaws.ecs.capability.logging-driver.awslogs"
    },
    {
      "targetId": null,
      "targetType": null,
      "value": null,
      "name": "com.amazonaws.ecs.capability.docker-remote-api.1.24"
    },
    {
      "targetId": null,
      "targetType": null,
      "value": null,
      "name": "com.amazonaws.ecs.capability.docker-remote-api.1.19"
    }
  ],
  "requiresCompatibilities": null,
  "networkMode": "host",
  "cpu": null,
  "revision": 2,
  "status": "ACTIVE",
  "volumes": []
}
